# These are supported funding model platforms

github: [chakravala]
patreon: dreamscatter
liberapay: chakravala
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://lulu.com/spotlight/chakravala
